### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pchaigno** [tbuser/openscad.tmbundle#2]
I would like to use your grammar for OpenSCAD but I don't know what licensing terms you're distributing it under. Any chance you could pick one from here: http://choosealicense.com?

**Comment by tbuser** [comment]
Oh yeah, I made it lgpl http://www.thingiverse.com/thing:15292

**Comment by pchaigno** [comment]
Great! Any chance you could include the license file in the repository?

**Comment by pchaigno** [comment]
@tbuser Could you add the license file in the repository? We need that to use the grammar at [github/linguist](https://github.com/github/linguist) and you probably have to distribute the license with the sources anyway...

**Comment by tbuser** [comment]
Added 4b2bc0a8e100d8f0350fd74f6c40dd956c118355

**Comment by pchaigno** [comment]
@tbuser Great! Thanks :yellow_heart:

**Comment by pchaigno** [comment]
@tbuser Your grammar is now used to highlight OpenSCAD code on GitHub (files and code snippets in Markdown)! (See github/linguist#2171 for more information.)
