### ISSUE TITLE
Would you consider re-licensing this repository?

### ISSUE THREAD

**Issue by arfon** [tbuser/openscad.tmbundle#3]
Hello there, we'd love to use this library to syntax-highlight files on GitHub but in order to do so we need this library to have a more permissive license.

If you don't have any particular reason for choosing GPL would you be willing to consider switching this to a more permissive license such as MIT, BSD or Apache 2?

Many thanks
Arfon (GitHub Staff)

**Comment by pchaigno** [comment]
@tbuser Did you get a chance to look into this?

**Comment by tbuser** [comment]
Wow, not sure how I missed this thread.  I just switched to MIT License. 87fae5d44058748b815c1bf070ab02fe5ad4f57e  Better late then never?

**Comment by pchaigno** [comment]
Awesome!

> Better late then never?

It sure is :smile: 

I'll add this grammar to [Linguist](https://github/github/linguist) when I get some time. That means you grammar will be used to highlight OpenSCAD files on github.com.
